apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.targetSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: {{ .Values.fakeSecret.key | quote }}
